### ISSUE TITLE
Reload Bip plugin

### ISSUE THREAD

**Issue by Noh3choo** [synacktiv/bip#3] opened 2020-08-19 19:52 UTC
While trying to develop and test Bip plugins it seems you must close IDA and start a new instance to have changes to `BipPlugin` subclasses take effect, this makes development and fixing bugs cumbersome. 

Can a function be added to `BipPluginManager` that will reload a given plugin(or all plugins)?

**Comment by BrunoPujos** [comment] 2020-08-20 17:05
Hello,

Thank you for the report.

You are totally right, there is actually nothing allowing to reload a plugin which is essential for testing :(

The problem is actually a little more complicated than expected because I forgot to add code for unloading plugins and there is a definite need to have functions for reloading one and all plugins. Below is a quick fix working with the last released and the current state of the master branch, other things after are just for me for tracking the fix for this issue.

If you have any problem with the quick fix do not hesitate to keep me inform and I will update this ticket as soon as I have a definitive fix.

## Quick fix

The following code should allow to reload a `BipPlugin`:

```python
def unreg_activities_bipplg(plg):
    """
        Unregister all the :class:`BipActivity` of a :class:`BipPlugin`.
    """
    for name, actions in plg._activities.items():
        actions.unregister()

def unload_bipplg(name):
    """
        "Unload" a :class:`BipPlugin` from its name. This will delete the
        reference maintain by the :class:`BipPluginManager` and remove the
        activities of the :class:`BipPlugin`. If the plugin "name" is not
        present it will do nothing.
    """
    bpm = get_plugin_manager()
    if name in bpm._loaded:
        p = bpm._loaded[name]
        unreg_activities_bipplg(p)
        del bpm._loaded[name]
    if name in bpm._plugins:
        del bpm._plugins[name]

def reload_bipplg(name, cls):
    """
        Unload a :class:`BipPlugin` with a particular name and load a new
        plugin with the same name. If no :class:`BipPlugin` by that name was
        previously loaded this will simply load the new plugin.
    """
    unload_bipplg(name)
    bpm = get_plugin_manager()
    bpm.addld_plugin(name, cls)
    #bpm._plugins[name] = cls
    #if not cls.to_load():
    #    return
    #p = cls()
    #bpm._loaded[name] = p
    #p.load()
    #return p
```

The `reload_bipplg` is the function which interests you, it should be usable the same way as the `addld_plugin` method (https://synacktiv.github.io/bip/build/html/gui/plgmanager.html#bip.gui.pluginmanager.BipPluginManager.addld_plugin). If your plugin is called `TstPlugin3` calling `reload_bipplg("TstPlugin3", TstPlugin3)` after having reimported the script with the plugin should allow you to have your changes take effect. In practice this unload the old one and load the new one.

## Test for implem

Code from Quick fix and following test BipPlugin:

```python
from bip import *

class TstPlugin3(BipPlugin):

    @classmethod
    def to_load(cls):
        print("ToLoad3")
        return True # always loading

    def load(self):
        print("In load3")
        super(TstPlugin3, self).load()
        print("After load3")
        print("After load3, new print3")
        
        
    @menu("Bip/Test3/", "Test with print")
    def test_pr(self):
        print("From menu")
```

Steps:

1. Load script with `TstPlugin3`
2. Use `bpm.addld_plugin` or `reload_bipplg` (quick fix) for loading `TstPlugin3`
3. Make change to `TstPlugin3`
4. Reload script with `TstPlugin3`
5. Make reload operation (`reload_bipplg`)
6. Test, including the Activities

## Steps for fixing

* Add a `_unregister_activities` for the `BipPlugin` object (see `unreg_activities_bipplg`)
* Add a `unload` method for the `BipPlugin` object which unregister the activities by default
* In the `BipPluginManager`:
    * Add a method for unloading a particular `BipPlugin`
    * Add a method for unloading all loaded `BipPlugin`
    * Add a method for reloading all `BipPlugin`
    * Add a method for reloading a particular `BipPlugin`
* Make test for all of those
* Doc all of those and add a section for how to easily test a plugin, also changelog
* (Fac.) Doc for the `add*` and `load*` method from `BipPluginManager` is bad, should be rewritten

This should not break existing API.

**Comment by BrunoPujos** [comment] 2020-08-26 09:37
The merge request #4 should fix this problem, it has been pushed on the `develop` branch. A `reload_plugin` method has been added to the `BipPluginManager` which should allow to easily reload a `BipPlugin` during the development of one.

Its usage should be comparable to the `reload_bipplg` function from the quick fix, reloading a plugin `TstPlugin3` once the class has been redefined can be done with the following code: `get_plugin_manager().reload_plugin(TstPlugin3)`.

Hopefully this will solve this issue, I am closing it but do not hesitate to re-open if you have any further problem/request.

**Closed by BrunoPujos** 2020-08-26 09:37 UTC
Labels: enhancement
